spring.application.name=SimpleSpringSecurityModule

spring.datasource.url=jdbc:mysql://localhost:3306/application
spring.datasource.username=root
spring.datasource.password=vinod267
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
server.port=9090
spring.jpa.show-sql=true
spring.jackson.default-property-inclusion=non_null
#Logger


management.endpoints.web.base-path=/manage
management.endpoints.web.exposure.include=*
management.server.port=1111
spring.lifecycle.timeout-per-shutdown-phase: 30s

